spring:
  datasource:
    url: jdbc:h2:mem:employees
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yaml
    url: jdbc:h2:mem:employees
logging:
  level:
    root: info